# -*- coding: utf-8 -*-
"""tools.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Q0s6UTo6a1VgKkIQgSSJK12gdv_zx-a

#Built in Tool DuckDuckGo Search
"""



from langchain_community.tools import DuckDuckGoSearchRun

search_tool = DuckDuckGoSearchRun()

result = search_tool.invoke('today match ipl')

print(result)

"""#custom tool

"""

from langchain_core.tools import tool

# step 1 - create a function

def multiply(a,b) :
  """ Multiply two number """
  return a*b

#step 2 - add type hints
def multiply (a:int , b:int) -> int:
  """multiply two number """
  return a * b

#step 3 - add tool decorator

@tool
def multiply(a:int , b:int) -> int:
  """ multiply two number """
  return a * b

result = multiply.invoke({"a" : 3, "b" : 5})
print(result)

print(multiply.name)
print(multiply.description)
print(multiply.args)

#when sending this tool to llm it sees it as

print(multiply.args_schema.model_json_schema())

